### ISSUE TITLE
Capire che PC sarà assegnato a questa Installazione

### ISSUE THREAD

**Issue by vongomben** [vongomben/smart-foot-brace#2]
Bisogna idenditifare un PC abbastanza performante per supportare questa installazione, PC che sarà quello che andrà in manifestazioni tipo Maker Faire Rome. 

Alternativamente potremmo usare un tablet creando una rete locale, ma questa soluzione é più distante perché richiede l'implementazione della comunicazione wireless, ancora lontana

**Comment by marioantonaci** [comment]
Ok per il PC. Cosa intendi per "abbastanza performante"?

**Comment by vongomben** [comment]
Probabilmente un comune PC portatile da ufficio funzionerà correttamente, ma occorre fare dei test
