### ISSUE TITLE
Passare a Arduino NANO 33 IoT

### ISSUE THREAD

**Issue by vongomben** [vongomben/smart-foot-brace#3]
Potrebbe essere interessante la migrazione del progetto a Arduino Nano 33 IoT, o magari avere due versioni del progetto

**Comment by marioantonaci** [comment]
Se l'acquisto è funzionale ad un invio dati via bluetooth o wifi, è necessario acquistare con rapidità

**Comment by vongomben** [comment]
Non lo é, tutte le schede che abbiamo lo permettono. L'ITS é in possesso di queste schede

**Comment by vongomben** [comment]
Ad oggi vorrei mantenere il deisgn basato su ESP32 per un tema di numero di pin 

Source: https://github.com/vongomben/smart-foot-brace/issues/10
